spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product?serverTimezone=UTC
    username: developer
    password: dev123456
#    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: personal.nathan.model.dataObject
